In [5]:
import pandas as pd
import numpy as np

In [6]:
emails = pd.read_csv('emails.csv')
emails.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [7]:
emails[emails.spam==0]

text  spam
1368  Subject: hello guys ,  i ' m " bugging you " f...     0
1369  Subject: sacramento weather station  fyi  - - ...     0
1370  Subject: from the enron india newsdesk - jan 1...     0
1371  Subject: re : powerisk 2001 - your invitation ...     0
1372  Subject: re : resco database and customer capt...     0
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[4360 rows x 2 columns]

In [8]:
emails.shape

(5728, 2)

In [9]:
(emails.spam.value_counts()/emails.shape[0] )*100

0    76.117318
1    23.882682
Name: spam, dtype: float64

In [10]:
emails.text=emails.text.apply(lambda x: x.replace('Subject:',''))
emails.text=emails.text.apply(lambda x: x.replace('subject:',''))
emails.text=emails.text.apply(lambda x: x.replace('Subject',''))
emails.text=emails.text.apply(lambda x: x.replace('subject',''))

In [11]:
emails.text

0        naturally irresistible your corporate identit...
1        the stock trading gunslinger  fanny is merril...
2        unbelievable new homes made easy  im wanting ...
3        4 color printing special  request additional ...
4        do not have money , get software cds from her...
                              ...                        
5723     re : research and development charges to gpg ...
5724     re : receipts from visit  jim ,  thanks again...
5725     re : enron case study update  wow ! all on th...
5726     re : interest  david ,  please , call shirley...
5727     news : aurora 5 . 2 update  aurora version 5 ...
Name: text, Length: 5728, dtype: object

In [12]:
def process_text(text):
    import re
    return re.sub(r'\d',"",text)

In [13]:
emails.text=emails.text.apply(lambda x : process_text(x))

In [31]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
matrix=CountVectorizer(lowercase=True,stop_words='english',min_df=0.1,ngram_range=(1,3),max_df=0.95)

In [15]:
#matrix=TfidfVectorizer(lowercase=True,stop_words='english',min_df=0.1,ngram_range=(1,3),max_df=0.95)

In [32]:
X=matrix.fit_transform(emails['text']).toarray()

In [33]:
X[0:10]

array([[ 0,  0,  0,  2,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         1,  1,  0,  2,  1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0

In [18]:
matrix.get_feature_names_out()

array(['attached', 'available', 'best', 'business', 'cc', 'com', 'com cc',
       'company', 'contact', 'corp', 'date', 'day', 'dear', 'ect',
       'ect cc', 'ect ect', 'ect ect cc', 'edu', 'email', 'energy',
       'enron', 'enron com', 'fax', 'following', 'forward', 'forwarded',
       'free', 'good', 'great', 'group', 'help', 'hi', 'hope', 'hou',
       'hou ect', 'hou ect ect', 'houston', 'http', 'information',
       'interested', 'just', 'kaminski', 'kaminski hou',
       'kaminski hou ect', 'know', 'let', 'let know', 'like', 'list',
       'look', 'mail', 'make', 'management', 'market', 'meeting',
       'message', 'need', 'new', 'number', 'office', 'people', 'phone',
       'pm', 'questions', 'regards', 'research', 'risk', 'send', 'sent',
       'shall', 'shirley', 'th', 'thank', 'thanks', 'think', 'time',
       'today', 'university', 'use', 'vince', 'vince kaminski',
       'vince kaminski hou', 'want', 'way', 'week', 'work', 'working',
       'www', 'year'], dtype=object)

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,emails['spam'],train_size=0.8,random_state=12345)

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [37]:
treemodel=DecisionTreeClassifier()
treemodel.fit(X_train,y_train)

DecisionTreeClassifier()

In [38]:
pred=treemodel.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [40]:
confusion_matrix(y_pred=pred,y_true=y_test)

array([[820,  32],
       [ 38, 256]])

In [41]:
accuracy_score(y_pred=pred,y_true=y_test)

0.9389179755671903

In [42]:
rf_model=RandomForestClassifier()
rf_model.fit(X_train,y_train)

RandomForestClassifier()

In [43]:
rf_pred=rf_model.predict(X_test)

In [44]:
confusion_matrix(y_pred=rf_pred,y_true=y_test)

array([[824,  28],
       [ 33, 261]])

In [ ]:
accuracy_score(y_pred=rf_pred,y_true=y_test)